apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bii-exceads-project-nfs-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      # This doesn't really matter for a static PV
      storage: 10Gi
  volumeMode: Filesystem
  volumeName: bii-exceads-project-nfs-pv
  storageClassName: bii-exceads-project-nfs-sc
