apiVersion: apps/v1
kind: Deployment
metadata:
  name: exceads-{{ .Values.environmentName }}-db-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: exceads
    environment: {{ .Values.environmentName }}
    component: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exceads
      environment: {{ .Values.environmentName }}
      component: db
  strategy:
    type: Recreate
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: exceads
        environment: {{ .Values.environmentName }}
        component: db
    spec:
      volumes:
        - name: bii-exceads-mysql-volume
          persistentVolumeClaim:
            claimName: bii-exceads-mysql-{{ .Values.environmentName }}-pvc
        - name: exceads-secrets
          secret:
            secretName: exceads-{{ .Values.environmentName }}-secrets
        - name: exceads-db-secrets
          secret:
            secretName: exceads-{{ .Values.environmentName }}-db-secrets
      containers:
      - name: exceads-{{ .Values.environmentName }}-db
        image: mysql:8.0.20
        ports:
        - containerPort: 3306
          name: mysql-exceads
        env:
          - name: MYSQL_DATABASE
            value: exceads
          - name: MYSQL_PASSWORD_FILE
            value: /run/exceads-db-secrets/db_exceads_password
          - name: MYSQL_ROOT_PASSWORD_FILE
            value: /run/exceads-db-secrets/db_root_password
          - name: MYSQL_USER
            value: exceads
        resources:
          requests:
            memory: "2048Mi"
            cpu: "1"
          limits:
            memory: "4096Mi"
            cpu: "2"
        volumeMounts:
        - name: exceads-db-secrets
          readOnly: true
          mountPath: "/run/exceads-db-secrets"
        - name: bii-exceads-mysql-volume
          mountPath: /var/lib/mysql
