apiVersion: apps/v1
kind: Deployment
metadata:
  name: exceads-{{ .Values.environmentName }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: exceads
    environment: {{ .Values.environmentName }}
    component: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exceads
      environment: {{ .Values.environmentName }}
      component: tomcat
  template:
    metadata:
      labels:
        app: exceads
        environment: {{ .Values.environmentName }}
        component: tomcat
    spec:
      volumes:
        - name: exceads-secrets
          secret:
            secretName: exceads-{{ .Values.environmentName }}-secrets
        - name: exceads-db-secrets
          secret:
            secretName: exceads-{{ .Values.environmentName }}-db-secrets
        
      imagePullSecrets:
        - name: exceads-registry-secret
      containers:
      - name: exceads-{{ .Values.environmentName }}-frontend
        image: {{ .Values.frontendImage }}:{{ .Values.frontendVersion }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http-exceads
        env:
            - name: EXCEADS_DB_PASSWORD_FILE
              value: /run/exceads-db-secrets/db_root_password
            - name: EXCEADS_DB_CONNECTION
              value: exceads-{{ .Values.environmentName }}-db-service:3306/exceads
            - name: EXCEADS_TEMPLATES_GIT_URL
              value: {{ .Values.exceadsTemplates.url }}
            - name: EXCEADS_GIT_TOKEN_FILE
              value: /run/exceads-secrets/git_token
            - name: EXCEADS_INSTANCE_NAME
              value: {{ .Values.sciductInstanceName }}
            - name: EXCEADS_SCIDUCT_TOKEN_FILE
              value: /run/exceads-secrets/sciduct_token
            - name: EXCEADS_SMTP_HOST
              value: {{ .Values.smtp.host }}
            - name: EXCEADS_SMTP_TO
              value: {{ .Values.smtp.to }}
        resources:
          requests:
            memory: "2048Mi"
            cpu: "0.5"
          limits:
            memory: "4096Mi"
            cpu: "2"
        volumeMounts:
        - name: exceads-db-secrets
          readOnly: true
          mountPath: "/run/exceads-db-secrets"
        - name: exceads-secrets
          readOnly: true
          mountPath: "/run/exceads-secrets"
