---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: exceads-{{ .Values.environmentName }}-secrets
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    git_token: {{ .Values.exceadsTemplates.sealedToken }}
    sciduct_token: {{ .Values.sciduct.sealedToken }}
  template:
    metadata:
      creationTimestamp: null
      name: exceads-{{ .Values.environmentName }}-secrets
      namespace: {{ .Release.Namespace }}
