---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: exceads-{{ .Values.environmentName }}-db-secrets
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    db_exceads_password: {{ .Values.exceadsDbSecrets.exceads }}
    db_root_password: {{ .Values.exceadsDbSecrets.root }}
  template:
    metadata:
      creationTimestamp: null
      name: exceads-{{ .Values.environmentName }}-db-secrets
      namespace: {{ .Release.Namespace }}
