apiVersion: v1
kind: Service
metadata:
  name: exceads-{{ .Values.environmentName }}-db-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: exceads
    environment: {{ .Values.environmentName }}
    component: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: mysql-exceads
