apiVersion: v1
kind: Service
metadata:
  name: exceads-{{ .Values.environmentName }}-tomcat-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: exceads
    environment: {{ .Values.environmentName }}
    component: tomcat
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http-exceads
