apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bii-exceads-mysql-{{ .Values.environmentName }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      # This doesn't really matter for a static PV
      storage: 2Gi
  volumeMode: Filesystem
  volumeName: bii-exceads-mysql-{{ .Values.environmentName }}-pv
  storageClassName: csi-rbd-sc
