---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: exceads-dev-db-secrets
  namespace: biocomplexity
spec:
  encryptedData:
    db_exceads_password: AgC+ses/04EwfbZljs3wH+Fu5wI75GHT3mGZW0nIhXbMS9wqg3dbgHtJ/EpVezRWFjOIvUB9mYLcr6RB6ySsUIxx18MU8Ij/n8efyxfd1ysPo3k7KNzuWe0ZS5AM0KIijwButh3f0lQYWYqx7yRLz7uu3kaNjdzF8qu6zSGydEmcyQUoRexvzJvZmFj0UyTyRNytJCzxv4wbDbeL8xzrRIv1JFxTA/Q//hwNRI7FWAa+VU0Gd1fhX/8F66axMNG7OZa2sQPf0OFdE7BZowTEakyKeBqmPnuRNtIxBQ3ssW9jQ4zqor1WTN0Q4bpKWjoblay6ZMXRTsqGGZ5EgmQYVndNKyWsXvfboEhdptaUbOsziwpDGHwRfd89+JMPd0byS+G9+bD7cs1uqkWe8Smmt/nOJzoK/WFiTJN7FtRcPU3Les/02VLexFPvUI2T8QwokBJsGjULekdoN92Uy9597j/rgtXWRgIR5ilj5pCbujZIJ8XF/VfXUTSqvvqwVkzR8X4uN1HInx+u/qrl+9dDq/f3sVIzqv4HUgtt8Wxd9qVIlxOnm/azbZNVPxj9U1T5TMuTS0ickQiyfNPa02rVCb6MRid3EwOpEcN+HPcTKxlGfyUnqyBHTR3HouTxeVE+vlU7dOGGLaJU8fhBJ5yN1HBvau3P617sDqQHofAqOczSILPlm7OjNVHICRWFPdqmH1lyU+2qRarQNp3eXD0gNCsi8Oy6lOw=
    db_root_password: AgC8Hx1LMziBrnYvy+ziWpk24TGKmX4xmNic468QMC3dNuRDztBanKfQPlp9Ij/ZvLEfksN4D1q+eMQRZA2MyckjTdJDmyvNTcNMX6EJ7qVOizd4bqVfK3DDVB6xCqaCBeF6+Msohzxk49G0uZ8hzxTZS65QOpzKUsS9szwi5d1KigsZbNehKTdovPCAgvBZ9Rcz34BuOlkP8gFjqEl+eZuNy1NNVSCewEStXHhtaV0lM+04JyfC9w1iunjes8yFI/Xwv4tAc2Q6uKL4yZ065wI5z4oGPIpPBPi3dFFslHp3+jd/0dYUl3rb+dkY1avMl+XWac1uT23QonqAPZKYIuHVZmxTtyn2eaWCk3oR0R6ATsqRpaVHPnjN6PTcVl46l5gR5KP4PehIhLxk9dhQ1ZtaLi6WlQc3dx3JSblmfllrf/unSCYC31eb4jI1clvx/BpOnlABbo2BOO109TigYMGFMsbLxJ+4tho7agpW5wTL2odm9QhaDPLvRwUZNoVrXeicRROoEnGz5MG4N3CC3CHEEVmfmDiLGvu5EFLMyGvxc8mXYa7sU37JJG3nlapskxmgqy/HxFUj6Ycg+kwVttxmb7aJfWwo2u4a3n4i9nNMLIKrEVdoHEZdkx1NeZKDYWTHk+GZkAchBwj61H+MvtKPeRz4Qdf0h0yLwsii3ds/zEoSFgNPHo3tScdh8s1lrMRML2reul9MV9WSiSGT1hOmohxLFRU=
  template:
    metadata:
      creationTimestamp: null
      name: exceads-dev-db-secrets
      namespace: biocomplexity
