---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: exceads-registry-secret
  namespace: biocomplexity
spec:
  encryptedData:
    .dockerconfigjson: AgCT8jEw8m9GrEvgYAYNpY+Os5kSYai/3eQuCHb78VgZtfabCyssbMgk6/kBbB8ZY9dQszLObZuwCt6eE5u9pzjYLp1w4SVyeDU1BE/hw7O0QD4H050J9Q0k9a0djt9MizVH+5XLBxMegKd7QmfojKmKxl3iaVBqlQKB+TAtqNdPeG/q+ifZ8FPUyH4qN04TDiDgAQj2MYZWlvDEWqtwfrZLCX+KJVwNNTq/4gKFlMS6vRrGl+hkFnTlLWMV1Y6QUKuwjZuPW87v0KDMTm3I6w7tQgPUMTNfCYeyKQa/q/xbZFyMEaE5QM7tcrS5vCLC3E1PJW5s7fGFcUjHm6qVVhJFW5R8wDlYpslY6+ashPuKGpT5R8gTXeg/bu2XmbJ1+F7ww7Xm51bdO1UgT8A3OS8DYH1EI+3fOeNueF3iEHsDV1b1rP9xS2trwu4ab0al7DnwMtqz3wseBLVAXELmEpyqcW86YoFBln9g88kRawwqY3dn4/jpPtUPD6tnfDjQAz58fiwM3FTT6xlEq1y73sdCZzoiklObE9E0aNE+MCD0R0p704D38mCblFoiWBKtDUIbb+1XP04saqCZ5dt4/VnSUYJBSFjLvjBTSSkYnos+VwhIzaSmHpit2bBvHM9ZrCAh6DMDqx8sBGYd77Qn/0sZjlCoQJTgk2AjypZudIpTtS6cgqvEKmZT9z9jbjJhDlcGSQ6t9rKm7uQ/b3KD+yYePN6Rf8O0vb4MnkWvsg7jlCNnwUM3FnU9RbuuTTfMM3B4OGTqq1prTEzS6bv7DoSnuPPlZo/4lj6YkQBwB5vUTGhESQagkvJQFQ60MnHiV7YgWjg0tMnhlnOT3h6cjsB8ZOIu
  template:
    metadata:
      creationTimestamp: null
      name: exceads-registry-secret
      namespace: biocomplexity
    type: kubernetes.io/dockerconfigjson
