apiVersion: v1
kind: Service
metadata:
  name: exceads-dev-db-service
  namespace: biocomplexity
spec:
  selector:
    app: exceads
    environment: dev
    component: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: mysql-exceads
